image: python:3.6

stages:
  - mirror
  
github_mirror:
  stage: mirror
  only:
    - master
  script:
    - git checkout master
    - git pull origin master
    - git push https://Ecklebe:GITHUB_OAUTH_TOKEN@github.com/Ecklebe/EmptyPythonProject.git master --force