image: python:3.6

stages:
  - install   
  - deploy
  - mirror
    
run_install_of_package:
  stage: install
  tags:
    - linux
    - python
  script:
    - python setup.py install

run_pyinstaller:
  stage: deploy
  tags:
    - linux
    - python
  script:
    - python setup.py install
    - python builder.py
  
github_mirror:
  stage: mirror
  only:
    - master
  script:
    - git checkout master
    - git pull origin master
    - git push https://Ecklebe:$GITHUB_OAUTH_TOKEN@github.com/Ecklebe/EmptyPythonProject.git master --force